export type Lang = 'en' | 'te'

export const business = {
  name: 'Murali Office Miny Lorry Transport',
  shortName: 'Murali Transport',
  owner: 'Murali Kallepalli',
  phone: '+919949705008',
  phoneAlt: '+918885075008',
  phoneDisplay: '9949705008',
  phoneAltDisplay: '8885075008',
  whatsapp: '919949705008',
  rating: '4.2',
  reviewCount: 27,
  mapsShareUrl: 'https://share.google/mAW3H8LK7Ogq0qrBl',
  mapsSearchUrl:
    'https://www.google.com/maps/search/?api=1&query=Murali+Office+Miny+Lorry+Transport+Dommeru',
  mapsEmbedUrl:
    'https://www.google.com/maps?q=17.031281,81.687531&z=16&output=embed',
  lat: 17.031281,
  lng: 81.687531,
}

export const address = {
  plusCode: '2MFM+F2V',
  locality: 'Dommeru',
  state: 'Andhra Pradesh',
  pin: '534342',
  country: 'India',
  line: '2MFM+F2V, Dommeru, Andhra Pradesh 534342, India',
}

/** Schematic route map (not GPS-precise) — Dommeru office hub to major cities. */
export const routeCities = [
  { id: 'hyderabad', en: 'Hyderabad', te: 'హైదరాబాద్', x: 70, y: 150, hub: false, major: true },
  { id: 'warangal', en: 'Warangal', te: 'వరంగల్', x: 140, y: 120, hub: false, major: true },
  { id: 'vijayawada', en: 'Vijayawada', te: 'విజయవాడ', x: 250, y: 280, hub: false, major: true },
  { id: 'guntur', en: 'Guntur', te: 'గుంటూరు', x: 230, y: 340, hub: false, major: true },
  { id: 'eluru', en: 'Eluru', te: 'ఏలూరు', x: 320, y: 270, hub: false, major: false },
  { id: 'tadepalli', en: 'Tadepalligudem', te: 'తాడేపల్లిగూడెం', x: 380, y: 250, hub: false, major: false },
  { id: 'nidadavole', en: 'Nidadavole', te: 'నిడదవోలు', x: 420, y: 230, hub: false, major: false },
  { id: 'dommeru', en: 'Dommeru', te: 'దొమ్మేరు', x: 500, y: 220, hub: true, major: false },
  { id: 'kovvur', en: 'Kovvur', te: 'కొవ్వూరు', x: 460, y: 190, hub: false, major: false },
  { id: 'rajahmundry', en: 'Rajahmundry', te: 'రాజమండ్రి', x: 580, y: 170, hub: false, major: true },
  { id: 'kakinada', en: 'Kakinada', te: 'కాకినాడ', x: 680, y: 180, hub: false, major: true },
  { id: 'vizag', en: 'Visakhapatnam', te: 'విశాఖపట్నం', x: 760, y: 110, hub: false, major: true },
  { id: 'tanuku', en: 'Tanuku', te: 'తణుకు', x: 400, y: 300, hub: false, major: false },
  { id: 'bhimavaram', en: 'Bhimavaram', te: 'భీమవరం', x: 390, y: 360, hub: false, major: false },
  { id: 'nellore', en: 'Nellore', te: 'నెల్లూరు', x: 280, y: 430, hub: false, major: true },
  { id: 'tirupati', en: 'Tirupati', te: 'తిరుపతి', x: 200, y: 480, hub: false, major: true },
  { id: 'chennai', en: 'Chennai', te: 'చెన్నై', x: 300, y: 520, hub: false, major: true },
] as const

export const routeLinks = [
  ['dommeru', 'kovvur'],
  ['dommeru', 'rajahmundry'],
  ['dommeru', 'nidadavole'],
  ['dommeru', 'tanuku'],
  ['dommeru', 'tadepalli'],
  ['kovvur', 'rajahmundry'],
  ['rajahmundry', 'kakinada'],
  ['kakinada', 'vizag'],
  ['nidadavole', 'eluru'],
  ['eluru', 'vijayawada'],
  ['tanuku', 'bhimavaram'],
  ['dommeru', 'vijayawada'],
  ['vijayawada', 'hyderabad'],
  ['hyderabad', 'warangal'],
  ['vijayawada', 'guntur'],
  ['guntur', 'nellore'],
  ['nellore', 'tirupati'],
  ['nellore', 'chennai'],
  ['tirupati', 'chennai'],
] as const

const dict = {
  en: {
    topStatsFallback: 'Trusted lorry booking office · Dommeru',
    hours: 'Open daily · 5:00 AM – 9:00 PM',
    navHome: 'Home',
    navServices: 'Services',
    navAbout: 'About',
    navRequest: 'Post load',
    navOwner: 'Register lorry',
    navAdmin: 'Admin',
    bookFreight: 'Book now',
    callNow: 'Call now',
    whatsapp: 'WhatsApp',
    heroKicker: 'Dommeru · Andhra Pradesh',
    heroBrand: 'Murali Transport Office',
    heroSub: 'Reliable mini lorry & truck booking',
    heroTagline: 'Twenty years matching loads and lorries from one Dommeru desk.',
    ctaQuote: 'Get a quote',
    trustStripTitle: 'Trusted local transport office',
    trustLiveLabel: 'Live at the office',
    trustRating: '4.2★ Google',
    trustReviews: '27 reviews',
    trustHours: 'Daily 5 AM – 9 PM',
    trustHub: 'Dommeru',
    finalCtaTitle: 'Ready to move cargo?',
    finalCtaBody: 'Speak with the Dommeru office or post your load — we match nearby lorries the same day.',
    whyTitle: 'Why choose Murali Transport?',
    whyIntro:
      'In the transport industry for the last 20 years — a reliable Dommeru office you can call and trust.',
    why1Title: '20 years in the industry',
    why1Body: 'Two decades of local freight experience behind every booking from Dommeru.',
    why2Title: 'Reliable dispatch',
    why2Body: 'Dependable pickup and delivery coordination with clear office follow-through.',
    why3Title: 'Location-aware matching',
    why3Body: 'We match open loads to lorries near the pickup for faster assignment.',
    why4Title: 'One office for both sides',
    why4Body: 'Post a load or register a lorry — the same Dommeru desk coordinates both.',
    serviceLearn: 'Open form',
    trustYears: '20 years',
    trustYearsDetail: 'In the industry',
    backLabel: '← Back',
    backHome: 'Back to home',
    roleTitle: 'How can we help?',
    roleShipperTitle: 'I have a load',
    roleShipperBody: 'Post pickup, drop, and cargo. We assign a nearby lorry.',
    roleCarrierTitle: 'I have a lorry',
    roleCarrierBody: 'Register plate, capacity, and location to get load calls.',
    roleOfficeTitle: 'Call the office',
    roleOfficeBody: 'Speak with Murali Transport for booking help right away.',
    findTitle: 'Start a booking',
    findPickupLabel: 'Where is the pickup?',
    findPickupPh: 'e.g. Dommeru, Kovvur, Rajahmundry',
    findEquipLabel: 'Vehicle type',
    findBtn: 'Continue',
    liveBoardTitle: 'Available now',
    liveBoardIntro: 'Open loads and free lorries with this office right now.',
    liveLorriesTitle: 'Available lorries',
    liveLoadsTitle: 'Open loads',
    liveEmptyLorries: 'No lorries marked available yet. Owners can register above.',
    liveEmptyLoads: 'No open loads right now. Post a load and we will match a lorry.',
    liveCapacity: 'Capacity',
    liveNear: 'Near',
    liveRoute: 'Route',
    liveWantLorry: 'Need a lorry for your cargo?',
    liveHaveLorry: 'Have a free lorry?',
    liveColPlate: 'Vehicle',
    liveColLoc: 'Location',
    liveColCap: 'Tons',
    liveColType: 'Type',
    liveColRoute: 'Route',
    liveColCargo: 'Cargo',
    liveColWhen: 'When',
    marketPulse: 'At the office now',
    routesTitle: 'Cities we connect',
    routesIntro: 'Our office is in Dommeru. From Dommeru we arrange mini lorries and trucks to major hubs.',
    routesHub: 'Office location',
    routesCover: 'Major hubs',
    routesNote: 'Need another destination? Call the Dommeru office and we will arrange it.',
    ctaPostLoad: 'Post a load',
    ctaRegister: 'Register lorry',
    ctaDirections: 'Get directions',
    servicesTitle: 'Our services',
    servicesIntro: 'Practical freight desk services for traders, farms, shops, and industries.',
    service1Title: 'Lorry / truck booking',
    service1Body:
      'Book mini lorries and trucks for local and long-distance cargo to major hubs from Dommeru.',
    service2Title: 'Load posting',
    service2Body:
      'Share pickup, drop, cargo, and weight. Our office receives the request and arranges a suitable vehicle.',
    service3Title: 'Vehicle registration',
    service3Body:
      'Lorry owners register plate, capacity, and current location so the office can assign nearby loads.',
    service4Title: 'Office dispatch',
    service4Body:
      'Admin matches open loads to available lorries by location and capacity — then confirms with both sides.',
    howTitle: 'How booking works',
    howIntro: 'Simple three-step process used by local transport offices.',
    how1Title: 'Tell us the load or register the lorry',
    how1Body: 'Post cargo details or list your vehicle with current location.',
    how2Title: 'Office reviews & matches',
    how2Body: 'We check availability and suggest lorries near the pickup point.',
    how3Title: 'Assign & dispatch',
    how3Body: 'Admin assigns the vehicle and shares driver / trip details for delivery.',
    testimonialsTitle: 'What customers say',
    testimonialsIntro: 'Local traders, farmers, and lorry owners who book with our Dommeru office.',
    aboutTitle: 'About us',
    aboutIntro:
      'Murali Office Miny Lorry Transport is a local commercial logistics booking office in Dommeru. We connect goods owners with mini lorries and trucks for safe, timely freight movement.',
    aboutOwnerLabel: 'Owner',
    aboutPhoneLabel: 'Phone',
    aboutAddressLabel: 'Office address',
    aboutHoursLabel: 'Working hours',
    aboutHoursValue: 'Daily, 5:00 AM – 9:00 PM',
    aboutBody:
      'Whether you need a mini lorry for a short local trip or a truck for longer routes, visit or call the Dommeru office. Vehicle owners can register with us to receive load assignments based on where their lorry is.',
    aboutMapTitle: 'Office on the map',
    googleReviews: 'Read Google reviews',
    formOfficeNote: 'Prefer to talk? Call or WhatsApp the Dommeru office — we book the same day during working hours.',
    fleetTitle: 'Reliable commercial fleet booking',
    fleetBody:
      'From Dommeru we arrange mini lorries and trucks for kirana stock, farm produce, construction material, and industrial cargo — with clear coordination from pickup to delivery.',
    trustFleet: 'Fleet on books',
    trustAvailable: 'available now',
    trustOpen: 'Open loads',
    trustOpenDetail: 'Waiting for office assignment',
    trustAssigned: 'Assigned trips',
    trustAssignedDetail: 'Matched by location & capacity',
    officeTitle: 'Visit the office',
    goAdmin: 'Admin desk',
    postTitle: 'Post a load',
    postIntro: 'Enter pickup, drop, and cargo details. The Dommeru office will assign a nearby lorry.',
    ownerTitle: 'Register your lorry',
    ownerIntro: 'List your vehicle with the transport office. Keep location updated for better load matches.',
    adminTitle: 'Transport office admin',
    adminIntro: 'Office desk for staff. Enter the PIN to unlock load matching and assignments.',
    adminPin: 'Admin PIN',
    adminStaffNote: 'Wrong PIN is limited: after 5 failed tries, login locks for 15 minutes.',
    searchLabel: 'Search',
    searchLoads: 'Search loads, places, phone, cargo…',
    searchFleet: 'Search plate, owner, driver, location…',
    searchAssign: 'Search plate, route, status…',
    listShowing: '{total} results · page {page}/{pages}',
    prevPage: 'Prev',
    nextPage: 'Next',
    noSearchResults: 'No matches for this search.',
    unlockDesk: 'Unlock desk',
    lockDesk: 'Lock desk',
    refresh: 'Refresh',
    deskActive: 'Desk session active',
    openLoads: 'Load requests',
    suggested: 'Match & assign',
    selectLoad: 'Open Load requests, select a load, then come back here to assign.',
    fleetSnap: 'Registered lorries',
    assignments: 'Active assignments',
    snapshotTitle: 'Desk snapshot',
    snapOpen: 'Open requests',
    snapAvailable: 'Available lorries',
    snapAssigned: 'Active trips',
    snapFleet: 'Total fleet',
    tabSnapshot: 'Snapshot',
    tabLoads: 'Loads',
    tabMatch: 'Match',
    tabFleet: 'Lorries',
    tabAssign: 'Assignments',
    panelLoadsHint: 'Edit, delete, or pick an open load to match',
    panelMatchHint: 'Location-ranked vehicles for the selected load',
    panelFleetHint: 'Edit or delete lorries registered with the office',
    panelAssignHint: 'Trips already matched — mark delivered when done',
    snapHint: 'Tap a tile or use the tabs above to open that desk view.',
    preferredDate: 'Preferred date',
    noOpen: 'No open loads right now.',
    noSuggest: 'No available vehicles match capacity yet.',
    noVehicles: 'No vehicles registered.',
    noAssign: 'No assignments yet.',
    assignBtn: 'Assign this lorry',
    editBtn: 'Edit',
    saveBtn: 'Save',
    cancelEditBtn: 'Cancel',
    deleteBtn: 'Delete',
    confirmDeleteLoad: 'Delete this load? Related assignments will be cleared.',
    confirmDeleteVehicle: 'Delete this lorry? Active trips will be cancelled.',
    allLoads: 'All loads',
    loadUpdated: 'Load updated.',
    loadDeleted: 'Load deleted.',
    vehicleUpdated: 'Lorry updated.',
    vehicleDeleted: 'Lorry deleted.',
    markDelivered: 'Mark delivered',
    loadDate: 'Preferred date',
    availableBadge: 'available',
    assignedBadge: 'assigned',
    openBadge: 'open',
    statusLabel: 'Status',
    requestor: 'Requestor',
    pickLoad: 'Select',
    selectedLoad: 'Selected',
    name: 'Your name',
    phone: 'Phone',
    pickup: 'Pickup location',
    dropoff: 'Drop location',
    cargo: 'Cargo',
    weight: 'Weight (tons)',
    vehiclePref: 'Vehicle preference',
    notes: 'Notes',
    submitLoad: 'Submit load request',
    confirmLoadTitle: 'Load request submitted',
    confirmVehicleTitle: 'Lorry registered',
    confirmBackHome: 'Back to home',
    confirmAnotherLoad: 'Post another load',
    confirmAnotherVehicle: 'Register another lorry',
    posting: 'Posting…',
    ownerName: 'Owner name',
    ownerPhone: 'Owner phone',
    driverName: 'Driver name',
    driverPhone: 'Driver phone',
    plate: 'Plate number',
    vehicleType: 'Vehicle type',
    capacity: 'Capacity (tons)',
    currentLoc: 'Current location',
    registerBtn: 'Register with office',
    saving: 'Saving…',
    any: 'Any',
    mini: 'Mini lorry',
    truck: 'Truck',
    partLoad: 'Part load',
    trailer: 'Trailer',
    footerRoles: 'Lorry owners · Load requestors · Office dispatch',
    footerNav: 'Quick links',
    footerPrivacy: 'Privacy policy',
    footerCopyright: '© {year} Murali Office Miny Lorry Transport, Dommeru. All rights reserved.',
    dockBook: 'Book',
    privacyTitle: 'Privacy policy',
    privacyIntro:
      'This policy explains how Murali Transport Office (Dommeru) handles information you share when you post a load, register a lorry, or contact us.',
    privacyS1Title: 'Information we collect',
    privacyS1Body:
      'When you use our booking forms we may collect your name, phone number, pickup and drop locations, cargo details, vehicle plate and capacity, and any notes you provide. Calls and WhatsApp messages to the office numbers may also include contact details you choose to share.',
    privacyS2Title: 'How we use information',
    privacyS2Body:
      'We use this information only to arrange mini lorry and truck bookings, match loads with available vehicles, contact you about dispatch, and improve office coordination. We do not sell your personal information.',
    privacyS3Title: 'Sharing',
    privacyS3Body:
      'Details needed for a trip may be shared with the assigned driver or vehicle owner and with office staff handling your booking. Public pages show only limited, masked availability information (for example masked routes or plates).',
    privacyS4Title: 'Storage & security',
    privacyS4Body:
      'Booking records are stored in our office systems so we can manage assignments. We take reasonable steps to protect access to admin tools. No method of transmission or storage is completely secure.',
    privacyS5Title: 'Your choices',
    privacyS5Body:
      'You may ask the Dommeru office to update or remove a load or vehicle registration you submitted, where that is practical and does not conflict with an active trip. Contact us using the office phone numbers listed on this site.',
    privacyS6Title: 'Changes',
    privacyS6Body:
      'We may update this policy from time to time. The updated version will be posted on this page with a revised date.',
    privacyContact: 'Questions about privacy? Call the Dommeru office:',
    privacyUpdated: 'Last updated: August 2026',
    localNow: 'Dommeru now',
    ist: 'IST',
    wxClear: 'Clear',
    wxCloud: 'Cloudy',
    wxRain: 'Rain',
    wxStorm: 'Storm',
    wxFog: 'Haze',
    langEn: 'EN',
    langTe: 'తెలుగు',
  },
  te: {
    topStatsFallback: 'నమ్మకమైన లారీ బుకింగ్ ఆఫీస్ · దొమ్మేరు',
    hours: 'ప్రతిరోజు · ఉదయం 5:00 – రాత్రి 9:00',
    navHome: 'హోమ్',
    navServices: 'సేవలు',
    navAbout: 'గురించి',
    navRequest: 'లోడ్ పోస్ట్',
    navOwner: 'లారీ రిజిస్టర్',
    navAdmin: 'అడ్మిన్',
    bookFreight: 'ఇప్పుడే బుక్ చేయండి',
    callNow: 'కాల్ చేయండి',
    whatsapp: 'వాట్సాప్',
    heroKicker: 'దొమ్మేరు · ఆంధ్రప్రదేశ్',
    heroBrand: 'మురళి ట్రాన్స్‌పోర్ట్ ఆఫీస్',
    heroSub: 'నమ్మకమైన మినీ లారీ & ట్రక్ బుకింగ్',
    heroTagline: 'ఇరవై సంవత్సరాలుగా దొమ్మేరు డెస్క్ నుండి లోడ్–లారీ మ్యాచింగ్.',
    ctaQuote: 'కోట్ పొందండి',
    trustStripTitle: 'నమ్మకమైన స్థానిక ట్రాన్స్‌పోర్ట్ ఆఫీస్',
    trustLiveLabel: 'ఆఫీస్‌లో ఇప్పుడు',
    trustRating: '4.2★ గూగుల్',
    trustReviews: '27 రివ్యూలు',
    trustHours: 'ప్రతిరోజు ఉదయం 5 – రాత్రి 9',
    trustHub: 'దొమ్మేరు',
    finalCtaTitle: 'సరుకు తరలించాలా?',
    finalCtaBody: 'దొమ్మేరు ఆఫీస్‌తో మాట్లాడండి లేదా లోడ్ పోస్ట్ చేయండి — సమీప లారీలను అదే రోజు మ్యాచ్ చేస్తాము.',
    whyTitle: 'మురళి ట్రాన్స్‌పోర్ట్ ఎందుకు?',
    whyIntro:
      'గత 20 సంవత్సరాలుగా ట్రాన్స్‌పోర్ట్ రంగంలో — నమ్మదగిన దొమ్మేరు ఆఫీస్.',
    why1Title: '20 సంవత్సరాల అనుభవం',
    why1Body: 'దొమ్మేరు నుండి ప్రతి బుకింగ్ వెనుక రెండు దశాబ్దాల స్థానిక ఫ్రైట్ అనుభవం.',
    why2Title: 'నమ్మకమైన డిస్పాచ్',
    why2Body: 'స్పష్టమైన ఆఫీస్ ఫాలో-అప్‌తో నమ్మదగిన పికప్ మరియు డెలివరీ సమన్వయం.',
    why3Title: 'లొకేషన్ ఆధారిత మ్యాచింగ్',
    why3Body: 'పికప్ దగ్గర లారీలతో ఓపెన్ లోడ్లను జత చేసి వేగంగా అసైన్ చేస్తాము.',
    why4Title: 'ఒకే ఆఫీస్ రెండు వైపులకు',
    why4Body: 'లోడ్ పోస్ట్ చేయండి లేదా లారీ నమోదు చేయండి — అదే దొమ్మేరు డెస్క్ సమన్వయం చేస్తుంది.',
    serviceLearn: 'ఫారమ్ తెరవండి',
    trustYears: '20 సంవత్సరాలు',
    trustYearsDetail: 'ఇండస్ట్రీలో',
    backLabel: '← వెనక్కి',
    backHome: 'హోమ్‌కు తిరిగి',
    roleTitle: 'మేము ఎలా సహాయం చేయగలం?',
    roleShipperTitle: 'నాకు లోడ్ ఉంది',
    roleShipperBody: 'పికప్, డ్రాప్, సరుకు ఇవ్వండి. సమీప లారీ కేటాయిస్తాము.',
    roleCarrierTitle: 'నాకు లారీ ఉంది',
    roleCarrierBody: 'ప్లేట్, కెపాసిటీ, స్థలం నమోదు చేసి లోడ్ కాల్స్ పొందండి.',
    roleOfficeTitle: 'ఆఫీస్‌కు కాల్',
    roleOfficeBody: 'బుకింగ్ సహాయం కోసం మురళి ట్రాన్స్‌పోర్ట్‌ను ఇప్పుడే కాల్ చేయండి.',
    findTitle: 'బుకింగ్ ప్రారంభించండి',
    findPickupLabel: 'పికప్ ఎక్కడ?',
    findPickupPh: 'ఉదా: దొమ్మేరు, కొవ్వూరు, రాజమండ్రి',
    findEquipLabel: 'వాహన రకం',
    findBtn: 'కొనసాగించండి',
    liveBoardTitle: 'ఇప్పుడు అందుబాటులో',
    liveBoardIntro: 'ఈ ఆఫీస్‌లో ఇప్పుడు ఉన్న ఓపెన్ లోడ్లు మరియు ఖాళీ లారీలు.',
    liveLorriesTitle: 'అందుబాటులో లారీలు',
    liveLoadsTitle: 'ఓపెన్ లోడ్లు',
    liveEmptyLorries: 'ఇంకా అందుబాటు లారీలు లేవు. యజమానులు నమోదు చేసుకోవచ్చు.',
    liveEmptyLoads: 'ఇప్పుడు ఓపెన్ లోడ్లు లేవు. లోడ్ పోస్ట్ చేస్తే లారీ కేటాయిస్తాము.',
    liveCapacity: 'కెపాసిటీ',
    liveNear: 'సమీపం',
    liveRoute: 'మార్గం',
    liveWantLorry: 'మీ సరుకుకు లారీ కావాలా?',
    liveHaveLorry: 'ఖాళీ లారీ ఉందా?',
    liveColPlate: 'వాహనం',
    liveColLoc: 'స్థలం',
    liveColCap: 'టన్నులు',
    liveColType: 'రకం',
    liveColRoute: 'మార్గం',
    liveColCargo: 'సరుకు',
    liveColWhen: 'ఎప్పుడు',
    marketPulse: 'ఆఫీస్‌లో ఇప్పుడు',
    routesTitle: 'మేము కలిపే పట్టణాలు',
    routesIntro: 'మా ఆఫీస్ దొమ్మేరులో ఉంది. దొమ్మేరు నుండి ప్రధాన హబ్‌లకు మినీ లారీలు, ట్రక్కులు ఏర్పాటు చేస్తాము.',
    routesHub: 'ఆఫీస్ స్థానం',
    routesCover: 'ప్రధాన హబ్‌లు',
    routesNote: 'మరో గమ్యం కావాలా? దొమ్మేరు ఆఫీస్‌కు కాల్ చేయండి — మేము ఏర్పాటు చేస్తాము.',
    ctaPostLoad: 'లోడ్ పోస్ట్ చేయండి',
    ctaRegister: 'లారీ నమోదు',
    ctaDirections: 'దారి చూపించు',
    servicesTitle: 'మా సేవలు',
    servicesIntro: 'వ్యాపారులు, రైతులు, దుకాణాలు, పరిశ్రమల కోసం ప్రామాణిక ఫ్రైట్ డెస్క్ సేవలు.',
    service1Title: 'లారీ / ట్రక్ బుకింగ్',
    service1Body:
      'దొమ్మేరు నుండి ప్రధాన హబ్‌లకు స్థానిక మరియు దూరపు సరుకు కోసం మినీ లారీలు, ట్రక్కులు బుక్ చేయండి.',
    service2Title: 'లోడ్ పోస్టింగ్',
    service2Body:
      'పికప్, డ్రాప్, సరుకు, బరువు వివరాలు ఇవ్వండి. ఆఫీస్ అభ్యర్థన అందుకొని సరైన వాహనం ఏర్పాటు చేస్తుంది.',
    service3Title: 'వాహన నమోదు',
    service3Body:
      'లారీ యజమానులు నంబర్, సామర్థ్యం, ప్రస్తుత స్థానం నమోదు చేసి సమీప లోడ్లు పొందవచ్చు.',
    service4Title: 'ఆఫీస్ డిస్పాచ్',
    service4Body:
      'అడ్మిన్ ఓపెన్ లోడ్లను అందుబాటులో ఉన్న లారీలతో స్థానం/సామర్థ్యం ఆధారంగా జత చేస్తారు.',
    howTitle: 'బుకింగ్ ఎలా జరుగుతుంది',
    howIntro: 'స్థానిక ట్రాన్స్‌పోర్ట్ ఆఫీసులు ఉపయోగించే సులభమైన మూడు దశల ప్రక్రియ.',
    how1Title: 'లోడ్ చెప్పండి లేదా లారీ నమోదు చేయండి',
    how1Body: 'సరుకు వివరాలు పోస్ట్ చేయండి లేదా మీ వాహనాన్ని ప్రస్తుత స్థానంతో జాబితా చేయండి.',
    how2Title: 'ఆఫీస్ సమీక్ష & మ్యాచ్',
    how2Body: 'అందుబాటు చూసి పికప్ సమీపంలోని లారీలను సూచిస్తాము.',
    how3Title: 'అసైన్ & డిస్పాచ్',
    how3Body: 'అడ్మిన్ వాహనం కేటాయించి డ్రైవర్ / ట్రిప్ వివరాలు పంపుతారు.',
    testimonialsTitle: 'వినియోగదారుల అభిప్రాయాలు',
    testimonialsIntro: 'దొమ్మేరు ఆఫీస్‌తో బుక్ చేసే వ్యాపారులు, రైతులు, లారీ యజమానుల మాటలు.',
    aboutTitle: 'మా గురించి',
    aboutIntro:
      'మురళి ఆఫీస్ మినీ లారీ ట్రాన్స్‌పోర్ట్ దొమ్మేరులోని స్థానిక వాణిజ్య లాజిస్టిక్స్ బుకింగ్ ఆఫీస్. సరుకు యజమానులను మినీ లారీలు/ట్రక్కులతో కలుపుతుంది.',
    aboutOwnerLabel: 'యజమాని',
    aboutPhoneLabel: 'ఫోన్',
    aboutAddressLabel: 'ఆఫీస్ చిరునామా',
    aboutHoursLabel: 'పని గంటలు',
    aboutHoursValue: 'ప్రతిరోజు, ఉదయం 5:00 – రాత్రి 9:00',
    aboutBody:
      'స్థానిక ప్రయాణం కోసం మినీ లారీ కావాలా లేదా దూర మార్గాలకు ట్రక్ కావాలా — దొమ్మేరు ఆఫీస్‌ను సంప్రదించండి. వాహన యజమానులు స్థానం ఆధారంగా లోడ్ అసైన్‌మెంట్లు పొందేందుకు నమోదు చేసుకోవచ్చు.',
    aboutMapTitle: 'మ్యాప్‌లో ఆఫీస్',
    googleReviews: 'గూగుల్ రివ్యూలు చూడండి',
    formOfficeNote: 'మాట్లాడాలనుకుంటే దొమ్మేరు ఆఫీస్‌కు కాల్ లేదా వాట్సాప్ చేయండి — పని గంటల్లో అదే రోజు బుక్ చేస్తాము.',
    fleetTitle: 'నమ్మకమైన వాణిజ్య వాహన బుకింగ్',
    fleetBody:
      'దొమ్మేరు నుండి కిరాణా, వ్యవసాయ ఉత్పత్తులు, నిర్మాణ సామగ్రి, పారిశ్రామిక సరుకు కోసం మినీ లారీలు మరియు ట్రక్కులు ఏర్పాటు చేస్తాము.',
    trustFleet: 'నమోదైన వాహనాలు',
    trustAvailable: 'ఇప్పుడు అందుబాటులో',
    trustOpen: 'ఓపెన్ లోడ్లు',
    trustOpenDetail: 'ఆఫీస్ అసైన్‌మెంట్ కోసం వేచి',
    trustAssigned: 'అసైన్ అయిన ట్రిప్‌లు',
    trustAssignedDetail: 'స్థానం & సామర్థ్యం ఆధారంగా',
    officeTitle: 'ఆఫీస్‌ను సందర్శించండి',
    goAdmin: 'అడ్మిన్ డెస్క్',
    postTitle: 'లోడ్ పోస్ట్ చేయండి',
    postIntro: 'పికప్, డ్రాప్, సరుకు వివరాలు ఇవ్వండి. దొమ్మేరు ఆఫీస్ సమీప లారీని కేటాయిస్తుంది.',
    ownerTitle: 'మీ లారీని నమోదు చేయండి',
    ownerIntro: 'ట్రాన్స్‌పోర్ట్ ఆఫీస్‌లో వాహనం నమోదు చేయండి. మెరుగైన మ్యాచ్‌ల కోసం స్థానం అప్‌డేట్ ఉంచండి.',
    adminTitle: 'ట్రాన్స్‌పోర్ట్ ఆఫీస్ అడ్మిన్',
    adminIntro: 'సిబ్బంది డెస్క్. లోడ్ మ్యాచింగ్ మరియు అసైన్‌మెంట్ల కోసం PIN ఎంటర్ చేయండి.',
    adminPin: 'అడ్మిన్ PIN',
    adminStaffNote: 'తప్పు PIN పరిమితం: 5 సార్లు తప్పు అయితే 15 నిమిషాలు లాక్ అవుతుంది.',
    searchLabel: 'సెర్చ్',
    searchLoads: 'లోడ్, స్థలం, ఫోన్, సరుకు సెర్చ్…',
    searchFleet: 'ప్లేట్, యజమాని, డ్రైవర్, స్థలం సెర్చ్…',
    searchAssign: 'ప్లేట్, మార్గం, స్థితి సెర్చ్…',
    listShowing: '{total} ఫలితాలు · పేజీ {page}/{pages}',
    prevPage: 'మునుపటి',
    nextPage: 'తర్వాత',
    noSearchResults: 'ఈ సెర్చ్‌కు మ్యాచ్‌లు లేవు.',
    unlockDesk: 'డెస్క్ అన్‌లాక్',
    lockDesk: 'డెస్క్ లాక్',
    refresh: 'రిఫ్రెష్',
    deskActive: 'డెస్క్ సెషన్ యాక్టివ్',
    openLoads: 'లోడ్ అభ్యర్థనలు',
    suggested: 'మ్యాచ్ & అసైన్',
    selectLoad: 'లోడ్ అభ్యర్థనలు ట్యాబ్ తెరిచి లోడ్ ఎంచుకుని, తర్వాత ఇక్కడకు వచ్చి అసైన్ చేయండి.',
    fleetSnap: 'రిజిస్టర్డ్ లారీలు',
    assignments: 'యాక్టివ్ అసైన్‌మెంట్లు',
    snapshotTitle: 'డెస్క్ స్నాప్‌షాట్',
    snapOpen: 'ఓపెన్ అభ్యర్థనలు',
    snapAvailable: 'అందుబాటులో లారీలు',
    snapAssigned: 'యాక్టివ్ ట్రిప్‌లు',
    snapFleet: 'మొత్తం ఫ్లీట్',
    tabSnapshot: 'స్నాప్‌షాట్',
    tabLoads: 'లోడ్లు',
    tabMatch: 'మ్యాచ్',
    tabFleet: 'లారీలు',
    tabAssign: 'అసైన్‌మెంట్లు',
    panelLoadsHint: 'సవరించండి, తొలగించండి లేదా ఓపెన్ లోడ్‌ను మ్యాచ్‌కు ఎంచుకోండి',
    panelMatchHint: 'ఎంచుకున్న లోడ్‌కు లొకేషన్ ర్యాంక్ వాహనాలు',
    panelFleetHint: 'ఆఫీస్‌లో నమోదైన లారీలను సవరించండి లేదా తొలగించండి',
    panelAssignHint: 'ఇప్పటికే మ్యాచ్ అయిన ట్రిప్‌లు — పూర్తయితే డెలివర్డ్ మార్క్ చేయండి',
    snapHint: 'టైల్ నొక్కండి లేదా పై ట్యాబ్‌లతో ఆ వీక్షణ తెరవండి.',
    preferredDate: 'ఇష్టమైన తేదీ',
    noOpen: 'ప్రస్తుతం ఓపెన్ లోడ్లు లేవు.',
    noSuggest: 'సామర్థ్యం సరిపోయే వాహనాలు ఇంకా లేవు.',
    noVehicles: 'వాహనాలు నమోదు కాలేదు.',
    noAssign: 'అసైన్‌మెంట్లు ఇంకా లేవు.',
    assignBtn: 'ఈ లారీని అసైన్ చేయి',
    editBtn: 'సవరించు',
    saveBtn: 'సేవ్',
    cancelEditBtn: 'రద్దు',
    deleteBtn: 'తొలగించు',
    confirmDeleteLoad: 'ఈ లోడ్ తొలగించాలా? సంబంధిత అసైన్‌మెంట్లు క్లియర్ అవుతాయి.',
    confirmDeleteVehicle: 'ఈ లారీ తొలగించాలా? యాక్టివ్ ట్రిప్‌లు రద్దవుతాయి.',
    allLoads: 'అన్ని లోడ్లు',
    loadUpdated: 'లోడ్ అప్‌డేట్ అయింది.',
    loadDeleted: 'లోడ్ తొలగించబడింది.',
    vehicleUpdated: 'లారీ అప్‌డేట్ అయింది.',
    vehicleDeleted: 'లారీ తొలగించబడింది.',
    markDelivered: 'డెలివరీ అయింది',
    loadDate: 'ఇష్టమైన తేదీ',
    availableBadge: 'అందుబాటులో',
    assignedBadge: 'అసైన్ అయింది',
    openBadge: 'ఓపెన్',
    statusLabel: 'స్థితి',
    requestor: 'అభ్యర్థి',
    pickLoad: 'ఎంచుకోండి',
    selectedLoad: 'ఎంచుకున్నది',
    name: 'మీ పేరు',
    phone: 'ఫోన్',
    pickup: 'పికప్ స్థలం',
    dropoff: 'డ్రాప్ స్థలం',
    cargo: 'సరుకు',
    weight: 'బరువు (టన్నులు)',
    vehiclePref: 'వాహన ప్రాధాన్యత',
    notes: 'గమనికలు',
    submitLoad: 'లోడ్ అభ్యర్థన పంపండి',
    confirmLoadTitle: 'లోడ్ అభ్యర్థన పంపబడింది',
    confirmVehicleTitle: 'లారీ నమోదు అయింది',
    confirmBackHome: 'హోమ్‌కు తిరిగి వెళ్లండి',
    confirmAnotherLoad: 'మరో లోడ్ పోస్ట్ చేయండి',
    confirmAnotherVehicle: 'మరో లారీ నమోదు చేయండి',
    posting: 'పంపుతోంది…',
    ownerName: 'యజమాని పేరు',
    ownerPhone: 'యజమాని ఫోన్',
    driverName: 'డ్రైవర్ పేరు',
    driverPhone: 'డ్రైవర్ ఫోన్',
    plate: 'వాహన నంబర్',
    vehicleType: 'వాహన రకం',
    capacity: 'సామర్థ్యం (టన్నులు)',
    currentLoc: 'ప్రస్తుత స్థానం',
    registerBtn: 'ఆఫీస్‌లో నమోదు',
    saving: 'సేవ్ అవుతోంది…',
    any: 'ఏదైనా',
    mini: 'మినీ లారీ',
    truck: 'ట్రక్',
    partLoad: 'పార్ట్ లోడ్',
    trailer: 'ట్రైలర్',
    footerRoles: 'లారీ యజమానులు · లోడ్ అభ్యర్థనలు · ఆఫీస్ డిస్పాచ్',
    footerNav: 'త్వరిత లింకులు',
    footerPrivacy: 'గోప్యతా విధానం',
    footerCopyright: '© {year} మురళి ఆఫీస్ మినీ లారీ ట్రాన్స్‌పోర్ట్, దొమ్మేరు. అన్ని హక్కులు కేటాయించబడ్డాయి.',
    dockBook: 'బుక్',
    privacyTitle: 'గోప్యతా విధానం',
    privacyIntro:
      'లోడ్ పోస్ట్, లారీ నమోదు లేదా మమ్మల్ని సంప్రదించినప్పుడు మురళి ట్రాన్స్‌పోర్ట్ ఆఫీస్ (దొమ్మేరు) మీ సమాచారాన్ని ఎలా నిర్వహిస్తుందో ఈ విధానం వివరిస్తుంది.',
    privacyS1Title: 'మేము సేకరించే సమాచారం',
    privacyS1Body:
      'బుకింగ్ ఫారమ్‌ల ద్వారా మీ పేరు, ఫోన్, పికప్/డ్రాప్, సరుకు వివరాలు, వాహన నంబర్/సామర్థ్యం మరియు మీరు ఇచ్చే గమనికలు సేకరించవచ్చు. ఆఫీస్ ఫోన్/వాట్సాప్ సంభాషణల్లో మీరు పంచుకున్న వివరాలు కూడా ఉండవచ్చు.',
    privacyS2Title: 'సమాచారం ఎలా ఉపయోగిస్తాము',
    privacyS2Body:
      'మినీ లారీ/ట్రక్ బుకింగ్, లోడ్–వాహన మ్యాచింగ్, డిస్పాచ్ కమ్యూనికేషన్ మరియు ఆఫీస్ సమన్వయం కోసం మాత్రమే ఉపయోగిస్తాము. మేము మీ వ్యక్తిగత సమాచారాన్ని అమ్మము.',
    privacyS3Title: 'పంచుకోవడం',
    privacyS3Body:
      'ట్రిప్‌కు అవసరమైన వివరాలు అసైన్ అయిన డ్రైవర్/యజమాని మరియు ఆఫీస్ సిబ్బందితో పంచుకోవచ్చు. పబ్లిక్ పేజీల్లో పరిమిత/మాస్క్ చేసిన సమాచారం మాత్రమే కనిపిస్తుంది.',
    privacyS4Title: 'నిల్వ & భద్రత',
    privacyS4Body:
      'అసైన్‌మెంట్లు నిర్వహించడానికి బుకింగ్ రికార్డులు ఆఫీస్ సిస్టమ్‌ల్లో నిల్వ ఉంటాయి. అడ్మిన్ యాక్సెస్‌ను రక్షించడానికి సహేతుక చర్యలు తీసుకుంటాము. ఏ నిల్వా పూర్తిగా సురక్షితం కాదు.',
    privacyS5Title: 'మీ ఎంపికలు',
    privacyS5Body:
      'మీరు పంపిన లోడ్ లేదా వాహన నమోదును అప్‌డేట్/తొలగించమని దొమ్మేరు ఆఫీస్‌ను అడగవచ్చు (యాక్టివ్ ట్రిప్‌తో విరుద్ధం కాకపోతే). సైట్‌లోని ఆఫీస్ ఫోన్ నంబర్‌లకు కాల్ చేయండి.',
    privacyS6Title: 'మార్పులు',
    privacyS6Body:
      'ఈ విధానాన్ని అప్పుడప్పుడు అప్‌డేట్ చేయవచ్చు. కొత్త వెర్షన్ ఈ పేజీలో తేదీతో ప్రచురించబడుతుంది.',
    privacyContact: 'గోప్యత గురించి ప్రశ్నలు ఉంటే దొమ్మేరు ఆఫీస్‌కు కాల్ చేయండి:',
    privacyUpdated: 'చివరి అప్‌డేట్: ఆగస్టు 2026',
    localNow: 'దొమ్మేరు ఇప్పుడు',
    ist: 'IST',
    wxClear: 'స్పష్టం',
    wxCloud: 'మేఘాలు',
    wxRain: 'వర్షం',
    wxStorm: 'తుఫాను',
    wxFog: 'పొగమంచు',
    langEn: 'EN',
    langTe: 'తెలుగు',
  },
} as const

export type Testimonial = {
  name: string
  place: string
  role: string
  quote: string
}

export const testimonials: Record<Lang, Testimonial[]> = {
  en: [
    {
      name: 'Venkateswara Rao',
      place: 'Rajahmundry',
      role: 'Hardware trader',
      quote: 'Posted a cement load in the morning and got a mini lorry from Dommeru the same day. Clear and fast.',
    },
    {
      name: 'Lakshmi Narayana',
      place: 'Kovvur',
      role: 'Farmer',
      quote: 'For paddy bags to the mill, Murali office found a nearby truck. Saved me calling many drivers.',
    },
    {
      name: 'Prasad Reddy',
      place: 'Dommeru',
      role: 'Kirana shop owner',
      quote: 'I book local grocery runs often. They know the routes and assign the right vehicle size.',
    },
    {
      name: 'Ramesh Babu',
      place: 'Nidadavole',
      role: 'Lorry owner',
      quote: 'Registered my Eicher here. Now I get load calls based on where my vehicle is parked.',
    },
    {
      name: 'Satyanarayana',
      place: 'Tanuku',
      role: 'Rice merchant',
      quote: 'Reliable office desk. Pickup and drop details were shared properly with the driver.',
    },
    {
      name: 'Srinivas Naidu',
      place: 'Eluru',
      role: 'Construction supplier',
      quote: 'Needed a truck for steel rods to site. Admin matched capacity well and trip went smooth.',
    },
    {
      name: 'Nagaraju',
      place: 'Bhimavaram',
      role: 'Warehouse manager',
      quote: 'WhatsApp and phone both work. Booking through the office is easier than hunting lorries myself.',
    },
    {
      name: 'Krishna Murthy',
      place: 'Tadepalligudem',
      role: 'Truck owner',
      quote: 'Good for part loads and full loads. Location matching helps me avoid empty return trips.',
    },
  ],
  te: [
    {
      name: 'వెంకటేశ్వర రావు',
      place: 'రాజమండ్రి',
      role: 'హార్డ్‌వేర్ వ్యాపారి',
      quote: 'ఉదయం సిమెంట్ లోడ్ పోస్ట్ చేశాను — అదే రోజు దొమ్మేరు నుండి మినీ లారీ వచ్చింది. వేగంగా, స్పష్టంగా.',
    },
    {
      name: 'లక్ష్మీ నారాయణ',
      place: 'కొవ్వూరు',
      role: 'రైతు',
      quote: 'వరి బస్తాలు మిల్లుకు పంపాలంటే మురళి ఆఫీస్ సమీప ట్రక్ ఏర్పాటు చేసింది. చాలా సులభం.',
    },
    {
      name: 'ప్రసాద్ రెడ్డి',
      place: 'దొమ్మేరు',
      role: 'కిరాణా దుకాణం',
      quote: 'లోకల్ కిరాణా రన్‌లు తరచు బుక్ చేస్తాను. మార్గాలు తెలుసు, సరైన వాహనం కేటాయిస్తారు.',
    },
    {
      name: 'రమేష్ బాబు',
      place: 'నిడదవోలు',
      role: 'లారీ యజమాని',
      quote: 'నా ఐచర్ ఇక్కడ రిజిస్టర్ చేశాను. వాహనం ఉన్న స్థలం ఆధారంగా లోడ్ కాల్స్ వస్తున్నాయి.',
    },
    {
      name: 'సత్యనారాయణ',
      place: 'తణుకు',
      role: 'బియ్యం వ్యాపారి',
      quote: 'నమ్మకమైన ఆఫీస్. పికప్, డ్రాప్ వివరాలు డ్రైవర్‌కు సరిగ్గా అందాయి.',
    },
    {
      name: 'శ్రీనివాస్ నాయుడు',
      place: 'ఏలూరు',
      role: 'నిర్మాణ సామగ్రి',
      quote: 'సైట్‌కు స్టీల్ రాడ్స్ కోసం ట్రక్ కావాలి. కెపాసిటీ సరిగ్గా మ్యాచ్ అయి ట్రిప్ సాఫీగా జరిగింది.',
    },
    {
      name: 'నాగరాజు',
      place: 'భీమవరం',
      role: 'గోదాము మేనేజర్',
      quote: 'వాట్సాప్, ఫోన్ రెండూ పని చేస్తాయి. స్వయంగా లారీ వెతకడం కంటే ఆఫీస్ ద్వారా బుకింగ్ సులభం.',
    },
    {
      name: 'కృష్ణ మూర్తి',
      place: 'తాడేపల్లిగూడెం',
      role: 'ట్రక్ యజమాని',
      quote: 'పార్ట్ లోడ్, ఫుల్ లోడ్ రెండింటికీ మంచిది. లొకేషన్ మ్యాచింగ్ వల్ల ఖాళీ రిటర్న్ తగ్గింది.',
    },
  ],
}

export type DictKey = keyof typeof dict.en

export function t(lang: Lang, key: DictKey): string {
  return dict[lang][key]
}
