export type Lang = 'en' | 'te'

export const business = {
  name: 'Murali Office Miny Lorry Transport',
  shortName: 'Murali Transport',
  owner: 'Murali Kallepalli',
  phone: '+919949705008',
  phoneDisplay: '99497 05008',
  whatsapp: '919949705008',
  rating: '4.2',
  reviewCount: 27,
  mapsShareUrl: 'https://share.google/mAW3H8LK7Ogq0qrBl',
  mapsSearchUrl:
    'https://www.google.com/maps/search/?api=1&query=Murali+Office+Miny+Lorry+Transport+Dommeru',
  lat: 17.031281,
  lng: 81.687531,
}

export const address = {
  plusCode: '2MFM+F2V',
  locality: 'Dommeru',
  state: 'Andhra Pradesh',
  pin: '534342',
  country: 'India',
  line: '2MFM+F2V, Dommeru, Andhra Pradesh 534342, India',
}

const dict = {
  en: {
    topStatsFallback: 'Trusted lorry booking office · Dommeru',
    hours: 'Open daily · 9:00 AM – 9:00 PM',
    navHome: 'Home',
    navServices: 'Services',
    navAbout: 'About',
    navRequest: 'Post load',
    navOwner: 'Register lorry',
    navAdmin: 'Admin',
    bookFreight: 'Book now',
    callNow: 'Call now',
    whatsapp: 'WhatsApp',
    heroKicker: 'Transport office · Dommeru, Andhra Pradesh',
    heroBrand: 'Murali Office',
    heroSub: 'Miny Lorry Transport',
    heroTagline:
      'Book mini lorries and trucks for your goods — or register your vehicle with our Dommeru office.',
    ctaPostLoad: 'Post a load',
    ctaRegister: 'Register your lorry',
    ctaDirections: 'Get directions',
    servicesTitle: 'Our services',
    servicesIntro: 'Standard freight desk services for traders, farms, shops, and industries.',
    service1Title: 'Lorry / truck booking',
    service1Body:
      'Book mini lorries and trucks for local and long-distance cargo across the Godavari belt and beyond.',
    service2Title: 'Load posting',
    service2Body:
      'Share pickup, drop, cargo, and weight. Our office receives the request and arranges a suitable vehicle.',
    service3Title: 'Vehicle registration',
    service3Body:
      'Lorry owners register plate, capacity, and current location so the office can assign nearby loads.',
    service4Title: 'Office dispatch',
    service4Body:
      'Admin matches open loads to available lorries by location and capacity — then confirms with both sides.',
    howTitle: 'How booking works',
    howIntro: 'Simple three-step process used by local transport offices.',
    how1Title: 'Tell us the load or register the lorry',
    how1Body: 'Post cargo details or list your vehicle with current location.',
    how2Title: 'Office reviews & matches',
    how2Body: 'We check availability and suggest lorries near the pickup point.',
    how3Title: 'Assign & dispatch',
    how3Body: 'Admin assigns the vehicle and shares driver / trip details for delivery.',
    aboutTitle: 'About us',
    aboutIntro:
      'Murali Office Miny Lorry Transport is a local commercial logistics booking office in Dommeru. We connect goods owners with mini lorries and trucks for safe, timely freight movement.',
    aboutOwnerLabel: 'Owner',
    aboutPhoneLabel: 'Phone',
    aboutAddressLabel: 'Office address',
    aboutHoursLabel: 'Working hours',
    aboutHoursValue: 'Daily, typically 9:00 AM – 9:00 PM',
    aboutBody:
      'Whether you need a mini lorry for a short local trip or a truck for longer routes, visit or call the Dommeru office. Vehicle owners can register with us to receive load assignments based on where their lorry is.',
    fleetTitle: 'Reliable commercial fleet booking',
    fleetBody:
      'From Dommeru we arrange mini lorries and trucks for kirana stock, farm produce, construction material, and industrial cargo — with clear coordination from pickup to delivery.',
    trustFleet: 'Fleet on books',
    trustAvailable: 'available now',
    trustOpen: 'Open loads',
    trustOpenDetail: 'Waiting for office assignment',
    trustAssigned: 'Assigned trips',
    trustAssignedDetail: 'Matched by location & capacity',
    officeTitle: 'Visit the office',
    goAdmin: 'Admin desk',
    postTitle: 'Post a load',
    postIntro: 'Enter pickup, drop, and cargo details. The Dommeru office will assign a nearby lorry.',
    ownerTitle: 'Register your lorry',
    ownerIntro: 'List your vehicle with the transport office. Keep location updated for better load matches.',
    adminTitle: 'Transport office admin',
    adminIntro: 'Receive load requests, review nearby lorries, and assign trips.',
    adminPin: 'Admin PIN',
    unlockDesk: 'Unlock desk',
    lockDesk: 'Lock desk',
    refresh: 'Refresh',
    deskActive: 'Desk session active',
    openLoads: 'Open loads',
    suggested: 'Suggested lorries',
    selectLoad: 'Select an open load to see location-ranked vehicles.',
    fleetSnap: 'Fleet snapshot',
    assignments: 'Assignments',
    noOpen: 'No open loads right now.',
    noSuggest: 'No available vehicles match capacity yet.',
    noVehicles: 'No vehicles registered.',
    noAssign: 'No assignments yet.',
    assignBtn: 'Assign this lorry',
    markDelivered: 'Mark delivered',
    name: 'Your name',
    phone: 'Phone',
    pickup: 'Pickup location',
    dropoff: 'Drop location',
    cargo: 'Cargo',
    weight: 'Weight (tons)',
    vehiclePref: 'Vehicle preference',
    preferredDate: 'Preferred date',
    notes: 'Notes',
    submitLoad: 'Submit load request',
    posting: 'Posting…',
    ownerName: 'Owner name',
    ownerPhone: 'Owner phone',
    plate: 'Plate number',
    vehicleType: 'Vehicle type',
    capacity: 'Capacity (tons)',
    currentLoc: 'Current location',
    registerBtn: 'Register with office',
    saving: 'Saving…',
    any: 'Any',
    mini: 'Mini lorry',
    truck: 'Truck',
    partLoad: 'Part load',
    trailer: 'Trailer',
    footerRoles: 'Lorry owners · Load requestors · Office dispatch',
    langEn: 'EN',
    langTe: 'తెలుగు',
  },
  te: {
    topStatsFallback: 'నమ్మకమైన లారీ బుకింగ్ ఆఫీస్ · దొమ్మేరు',
    hours: 'ప్రతిరోజు · ఉదయం 9:00 – రాత్రి 9:00',
    navHome: 'హోమ్',
    navServices: 'సేవలు',
    navAbout: 'గురించి',
    navRequest: 'లోడ్ పోస్ట్',
    navOwner: 'లారీ రిజిస్టర్',
    navAdmin: 'అడ్మిన్',
    bookFreight: 'ఇప్పుడే బుక్ చేయండి',
    callNow: 'కాల్ చేయండి',
    whatsapp: 'వాట్సాప్',
    heroKicker: 'ట్రాన్స్‌పోర్ట్ ఆఫీస్ · దొమ్మేరు, ఆంధ్రప్రదేశ్',
    heroBrand: 'మురళి ఆఫీస్',
    heroSub: 'మినీ లారీ ట్రాన్స్‌పోర్ట్',
    heroTagline:
      'మీ సరుకు కోసం మినీ లారీ/ట్రక్ బుక్ చేసుకోండి — లేదా మీ వాహనాన్ని దొమ్మేరు ఆఫీస్‌లో నమోదు చేయండి.',
    ctaPostLoad: 'లోడ్ పోస్ట్ చేయండి',
    ctaRegister: 'మీ లారీని నమోదు చేయండి',
    ctaDirections: 'దారి చూపించు',
    servicesTitle: 'మా సేవలు',
    servicesIntro: 'వ్యాపారులు, రైతులు, దుకాణాలు, పరిశ్రమల కోసం ప్రామాణిక ఫ్రైట్ డెస్క్ సేవలు.',
    service1Title: 'లారీ / ట్రక్ బుకింగ్',
    service1Body:
      'గోదావరి ప్రాంతం మరియు ఇతర మార్గాల్లో స్థానిక మరియు దూరపు సరుకు కోసం మినీ లారీలు, ట్రక్కులు బుక్ చేయండి.',
    service2Title: 'లోడ్ పోస్టింగ్',
    service2Body:
      'పికప్, డ్రాప్, సరుకు, బరువు వివరాలు ఇవ్వండి. ఆఫీస్ అభ్యర్థన అందుకొని సరైన వాహనం ఏర్పాటు చేస్తుంది.',
    service3Title: 'వాహన నమోదు',
    service3Body:
      'లారీ యజమానులు నంబర్, సామర్థ్యం, ప్రస్తుత స్థానం నమోదు చేసి సమీప లోడ్లు పొందవచ్చు.',
    service4Title: 'ఆఫీస్ డిస్పాచ్',
    service4Body:
      'అడ్మిన్ ఓపెన్ లోడ్లను అందుబాటులో ఉన్న లారీలతో స్థానం/సామర్థ్యం ఆధారంగా జత చేస్తారు.',
    howTitle: 'బుకింగ్ ఎలా జరుగుతుంది',
    howIntro: 'స్థానిక ట్రాన్స్‌పోర్ట్ ఆఫీసులు ఉపయోగించే సులభమైన మూడు దశల ప్రక్రియ.',
    how1Title: 'లోడ్ చెప్పండి లేదా లారీ నమోదు చేయండి',
    how1Body: 'సరుకు వివరాలు పోస్ట్ చేయండి లేదా మీ వాహనాన్ని ప్రస్తుత స్థానంతో జాబితా చేయండి.',
    how2Title: 'ఆఫీస్ సమీక్ష & మ్యాచ్',
    how2Body: 'అందుబాటు చూసి పికప్ సమీపంలోని లారీలను సూచిస్తాము.',
    how3Title: 'అసైన్ & డిస్పాచ్',
    how3Body: 'అడ్మిన్ వాహనం కేటాయించి డ్రైవర్ / ట్రిప్ వివరాలు పంపుతారు.',
    aboutTitle: 'మా గురించి',
    aboutIntro:
      'మురళి ఆఫీస్ మినీ లారీ ట్రాన్స్‌పోర్ట్ దొమ్మేరులోని స్థానిక వాణిజ్య లాజిస్టిక్స్ బుకింగ్ ఆఫీస్. సరుకు యజమానులను మినీ లారీలు/ట్రక్కులతో కలుపుతుంది.',
    aboutOwnerLabel: 'యజమాని',
    aboutPhoneLabel: 'ఫోన్',
    aboutAddressLabel: 'ఆఫీస్ చిరునామా',
    aboutHoursLabel: 'పని గంటలు',
    aboutHoursValue: 'ప్రతిరోజు, సాధారణంగా ఉదయం 9:00 – రాత్రి 9:00',
    aboutBody:
      'స్థానిక ప్రయాణం కోసం మినీ లారీ కావాలా లేదా దూర మార్గాలకు ట్రక్ కావాలా — దొమ్మేరు ఆఫీస్‌ను సంప్రదించండి. వాహన యజమానులు స్థానం ఆధారంగా లోడ్ అసైన్‌మెంట్లు పొందేందుకు నమోదు చేసుకోవచ్చు.',
    fleetTitle: 'నమ్మకమైన వాణిజ్య వాహన బుకింగ్',
    fleetBody:
      'దొమ్మేరు నుండి కిరాణా, వ్యవసాయ ఉత్పత్తులు, నిర్మాణ సామగ్రి, పారిశ్రామిక సరుకు కోసం మినీ లారీలు మరియు ట్రక్కులు ఏర్పాటు చేస్తాము.',
    trustFleet: 'నమోదైన వాహనాలు',
    trustAvailable: 'ఇప్పుడు అందుబాటులో',
    trustOpen: 'ఓపెన్ లోడ్లు',
    trustOpenDetail: 'ఆఫీస్ అసైన్‌మెంట్ కోసం వేచి',
    trustAssigned: 'అసైన్ అయిన ట్రిప్‌లు',
    trustAssignedDetail: 'స్థానం & సామర్థ్యం ఆధారంగా',
    officeTitle: 'ఆఫీస్‌ను సందర్శించండి',
    goAdmin: 'అడ్మిన్ డెస్క్',
    postTitle: 'లోడ్ పోస్ట్ చేయండి',
    postIntro: 'పికప్, డ్రాప్, సరుకు వివరాలు ఇవ్వండి. దొమ్మేరు ఆఫీస్ సమీప లారీని కేటాయిస్తుంది.',
    ownerTitle: 'మీ లారీని నమోదు చేయండి',
    ownerIntro: 'ట్రాన్స్‌పోర్ట్ ఆఫీస్‌లో వాహనం నమోదు చేయండి. మెరుగైన మ్యాచ్‌ల కోసం స్థానం అప్‌డేట్ ఉంచండి.',
    adminTitle: 'ట్రాన్స్‌పోర్ట్ ఆఫీస్ అడ్మిన్',
    adminIntro: 'లోడ్ అభ్యర్థనలు అందుకొని, సమీప లారీలను చూసి ట్రిప్‌లు కేటాయించండి.',
    adminPin: 'అడ్మిన్ PIN',
    unlockDesk: 'డెస్క్ అన్‌లాక్',
    lockDesk: 'డెస్క్ లాక్',
    refresh: 'రిఫ్రెష్',
    deskActive: 'డెస్క్ సెషన్ యాక్టివ్',
    openLoads: 'ఓపెన్ లోడ్లు',
    suggested: 'సూచించిన లారీలు',
    selectLoad: 'స్థానం ఆధారిత వాహనాలు చూడటానికి ఓపెన్ లోడ్ ఎంచుకోండి.',
    fleetSnap: 'ఫ్లీట్ స్నాప్‌షాట్',
    assignments: 'అసైన్‌మెంట్లు',
    noOpen: 'ప్రస్తుతం ఓపెన్ లోడ్లు లేవు.',
    noSuggest: 'సామర్థ్యం సరిపోయే వాహనాలు ఇంకా లేవు.',
    noVehicles: 'వాహనాలు నమోదు కాలేదు.',
    noAssign: 'అసైన్‌మెంట్లు ఇంకా లేవు.',
    assignBtn: 'ఈ లారీని అసైన్ చేయి',
    markDelivered: 'డెలివరీ అయింది',
    name: 'మీ పేరు',
    phone: 'ఫోన్',
    pickup: 'పికప్ స్థలం',
    dropoff: 'డ్రాప్ స్థలం',
    cargo: 'సరుకు',
    weight: 'బరువు (టన్నులు)',
    vehiclePref: 'వాహన ప్రాధాన్యత',
    preferredDate: 'ఇష్టపడే తేదీ',
    notes: 'గమనికలు',
    submitLoad: 'లోడ్ అభ్యర్థన పంపండి',
    posting: 'పంపుతోంది…',
    ownerName: 'యజమాని పేరు',
    ownerPhone: 'యజమాని ఫోన్',
    plate: 'వాహన నంబర్',
    vehicleType: 'వాహన రకం',
    capacity: 'సామర్థ్యం (టన్నులు)',
    currentLoc: 'ప్రస్తుత స్థానం',
    registerBtn: 'ఆఫీస్‌లో నమోదు',
    saving: 'సేవ్ అవుతోంది…',
    any: 'ఏదైనా',
    mini: 'మినీ లారీ',
    truck: 'ట్రక్',
    partLoad: 'పార్ట్ లోడ్',
    trailer: 'ట్రైలర్',
    footerRoles: 'లారీ యజమానులు · లోడ్ అభ్యర్థనలు · ఆఫీస్ డిస్పాచ్',
    langEn: 'EN',
    langTe: 'తెలుగు',
  },
} as const

export type DictKey = keyof typeof dict.en

export function t(lang: Lang, key: DictKey): string {
  return dict[lang][key]
}
